### ISSUE TITLE
Specify keyboardType of TextInputs

### ISSUE THREAD

**Issue by januswel** [react-native-jp/praiser#4]
![Oct-27-2019 20-01-38](https://user-images.githubusercontent.com/43239/67633568-a70f0980-f8f4-11e9-8b12-bbe90d6d4c85.gif)

**Comment by YutamaKotaro** [comment]
コレなにが問題なんでしたっけ？

**Comment by januswel** [comment]
最初の一文字が勝手に大文字変換されてしまうので、入力時にフラストレーションがたまるという問題です
今見たら治っているので close
