### ISSUE TITLE
TypeError: Cannot read property 'getRandomBase64' of undefined    ]

### ISSUE THREAD

**Issue by hogehoge-satosato** [react-native-jp/praiser#72]
こんにちは、React Nativeの本の読者です。

P５４４～５４５をコードにしているのですが、UUIDがうまくいかず、タイトルのエラーが出ます。
Jestによるテストが進まず、困っています。

色々調べてためしたのですが、うまくいきません。
https://stackoverflow.com/questions/64165922/error-cannot-read-property-getrandombase64-of-undefined-when-running-test-file
↑　を試しましたが、だめでした。
こちらのGitHubに提供されているコードを丸コピーして入れてもうまくいきませんでした。

アプリの実相のこれまでのところは、うまくいっていました。

こちらはかなりの初心者です。
八方ふさがりで困っています。
心苦しいのですが、ご助言いただけますと助かります。

環境は、Windows１０HOME
エディタは、VSCodeです。
よろしくお願いします。

**Comment by hogehoge-satosato** [comment]
<img width="938" alt="スクリーンショット 2021-01-06 103001" src="https://user-images.githubusercontent.com/75717574/103718566-5de33b00-500a-11eb-8cf9-11ae5a789280.png">


コマンドプロンプトのエラー画面です。
VSCodeでも同じです。

**Comment by kyamashiro** [comment]
package.jsonのreact-native-get-random-valuesのバージョンは"1.3.0"でしょうか？
こちらの環境で試したところ"1.4.0","1.5.0"だとテストでエラーになるようです。

`_mocks_`ディレクトリ直下に空の`react-native-get-random-values.js`ファイルを作成するか、もしくはこちらの[issue](https://github.com/LinusU/react-native-get-random-values/issues/22)にあるようにテストファイル内のdescribeの前に

```js
jest.mock('react-native-get-random-values', () => ({
  getRandomBase64: jest.fn(),
}));
```
モックを追加してあげればテストで失敗しなくなるようです。

**Comment by hogehoge-satosato** [comment]
ありがとうございます。
試してみます。

2021年1月8日(金) 19:55 kyamashiro <notifications@github.com>:

**Comment by hogehoge-satosato** [comment]
ターミナルで
  `yarn add react-native-get-random-values@1.3.0`
実行したところ、うまくいきました！！
すごく助かりました。
ありがとうございます（T T）

**Comment by januswel** [comment]
@hogehoge-satosato 
ご連絡ありがとうございます
確認が遅くなってすみません
いただいた情報は編集に連絡して正誤表に載せてもらいます

@kyamashiro 
フォローありがとうございます

**Comment by hogehoge-satosato** [comment]
お正月の忙しい時期にご対応いただきありがとうございました😊
心から感謝しております。

とてもいい本だと思うので、より多くの方々に読んで欲しいと願っています。

次の本も楽しみにしております。

2021年1月11日(月) 22:45 Takagi Kensuke <notifications@github.com>:
